### ISSUE TITLE
建议更换放送时间数据源

### ISSUE THREAD

**Issue by zhyu** [wxt2005/bangumi-list#11]
http://cal.syoboi.jp/ 有更详细、准确的数据，并且提供了 [API](https://sites.google.com/site/syobocal/spec)

API 的使用可以参考我的 [Telegram Bot](https://github.com/zhyu/hemera/blob/master/lib/hemera/anime.ex#L45-L51)

**Comment by weizhenye** [comment]
@zhyu 不太懂日语，没怎么看明白。
几个问题：
1. 如果要获取所有 16 年夏番，有直接的 API 吗？还是需要自己根据时间过滤？
2. 对于某一番组，可以获取其第一集放送时间吗？看了下 `http://cal.syoboi.jp/db.php?Command=TitleLookup&TID=4207` 似乎没有。需要通过某个 API 获取所有时间再筛选吗？

看上去 cal.syoboi.jp 的数据定位似乎与 bangumi-list 不太符合。bangumi-list 并不保存番组每集确切的放送时间，其需求为每季度获取完整的新番列表，记录番组最早的放送时间。
