### ISSUE TITLE
希望在设置内可以设置 Bangumi 的域名

### ISSUE THREAD

**Issue by BinotaLiu** [wxt2005/bangumi-list#20]
目前 Bangumi 提供了三个可用域名：
* bgm.tv
* bangumi.tv
* chii.in

bangumi-list 默认是使用 `bangumi.tv` ，
然而并不是每个人都使用这个域名，
希望可以在设置中增加 Bangumi 域名的选项。

**Comment by wxt2005** [comment]
已添加选项 ebf64a5cdc6092919df75ca3e0982e723d4cd7f7
