### ISSUE TITLE
支持用拼音搜索

### ISSUE THREAD

**Issue by fancl20** [wxt2005/bangumi-list#23]
支持用拼音搜索
可以使用 https://github.com/hotoo/pinyin

**Comment by no1xsyzy** [comment]
需要上游数据源先行支持
已发issue：https://github.com/bangumi-data/bangumi-data/issues/21

**Comment by 22earth** [comment]
#49 之前我简单的加入了拼音首字母搜索的功能。全拼搜索感觉那个库有些大，影响效率 就没有用
