### ISSUE TITLE
Why not make a npm publish

### ISSUE THREAD

**Issue by micooz** [wxt2005/bangumi-list#25]
Did not find your package on [npmjs.com](https://www.npmjs.com/), I recommend you to make a publish. Somebody has a further plan to your awesome project :)

**Comment by wxt2005** [comment]
Hey, thanks for your attention.

Currently I will not publish this project to npm, for reasons below:

1. It's not stable enough to become a public package. This project's main purpose is for studying, maybe I will do many breaking  changes just for experiment. 

1. The way I update bangumi data. This project don't have a back-end server or database, thus all data are stored in separate json files. It's ok for now, but as a public package, I think is problematic.

Recently I am working on an API server for bangumi-list, and considering rewrite front-end code again (Yeah, rewrite!). If you (or somebody) are planing to do some fantastic things based on this project, I think forking will be the best way :smile:

**Comment by micooz** [comment]
Looking forward to your excellent work!
