### ISSUE TITLE
是否考虑添加 S1 专楼地址？

### ISSUE THREAD

**Issue by weizhenye** [wxt2005/bangumi-list#27]
毕竟华语第 X。
貌似绝大多数动画在 S1 都是单个帖子作为专楼的，少数动画例如革命机是一集一个帖子的。一季二季有无分开应该没什么影响。我 S1 上得少，只能想到这些情况。
如果可以添加的话，确定好数据格式规范，我来发 PR。

**Comment by wxt2005** [comment]
感觉暂时没什么必要，S1 这地方，有瘾的人根本不需要有个快捷入口……
主要是想保持功能简洁，暂时没还打算做成一个番组相关信息聚合站。
