### ISSUE TITLE
如何修改播放源顺序？

### ISSUE THREAD

**Issue by dxhuii** [wxt2005/bangumi-list#43]
如题

**Comment by dxhuii** [comment]
@wxt2005 有没有地方可以修改呢？

**Comment by wxt2005** [comment]
不好意思，暂时还没有这样的功能。现在是写死的排序。

**Comment by dxhuii** [comment]
@wxt2005  没事，那我手动改一下。

**Comment by dxhuii** [comment]
排序的问题解决了：找到 ItemSites.js 文件，注释掉

` .sortBy(function(url){
                 return Utils.getLinkSite(url, this.props.supportSites).name;
             }.bind(this))`
就能按自己写的顺序输出网站 顺序了。
