### ISSUE TITLE
太慢了！每次出季度新番数据都更新的很慢！

### ISSUE THREAD

**Issue by lirener** [wxt2005/bangumi-list#51]
太慢了！每次出季度新番数据都更新的很慢！
我就直接说了吧弄个提交数据群！
以下反馈2017年10月的 上次07月也是太慢了……
つうかあ已经翻译为侧车搭档 由A站独家
黑色五叶草也少了片叶子更名为黑色四叶草...

**Comment by yunchenran** [comment]
现在直接被墙了已经~

**Comment by lirener** [comment]
随便啊 反正会翻……这个问题解决了 可以隐藏了

**Comment by wxt2005** [comment]
不好意思最近工作忙成狗，等我有时间切个服务器吧。
