### ISSUE TITLE
你的网站打不开了，好多天了。

### ISSUE THREAD

**Issue by dxhuii** [wxt2005/bangumi-list#56]
你的网站打不开了，好多天了。

**Comment by wxt2005** [comment]
我这边貌似没有问题，能提供下你的网络环境和使用的浏览器吗？有没有尝试过使用其它浏览器打开呢？

**Comment by dxhuii** [comment]
@wxt2005 www.ip138.com iP查询(搜索iP地址的地理位置)
您的IP是：[116.226.161.238] 来自：上海市 电信

版本 65.0.3325.162  chrome

**Comment by dxhuii** [comment]
现在可以打开了。
