### ISSUE TITLE
番表都7月2号了还没有更新，这次更新有点晚

### ISSUE THREAD

**Issue by dxhuii** [wxt2005/bangumi-list#57]
RT

**Comment by wxt2005** [comment]
不好意思，自动更新的脚本出了点问题。现在已经更新了

**Comment by dxhuii** [comment]
嗯嗯。脚本开源吗？我一直用你的数据，哈哈。www.ikanfan.cn 我自己更新新番参考。然后加了点东西。

**Comment by dxhuii** [comment]
可是那边数据不能像这样生成，上一季没有播完的+当季播放的JSON数据。我去问 了，他们说只提供数据，没有生成你种数据的命令。

**Comment by wxt2005** [comment]
这个其实你自己写一个脚本跑一下番组的开播和结束时间就可以了，我这边有个私有的 API 服务器，但是随便写的，暂时没打算开源。

**Comment by dxhuii** [comment]
嗯，好吧。
