### ISSUE TITLE
关于 bangumi 的域名

### ISSUE THREAD

**Issue by no1xsyzy** [wxt2005/bangumi-list#62]
延续 #52 ，追加近况
现在三个域名都支持 HTTPS，并且加入了 HTTPS Everywhere 的数据库，但并未启动 HSTS。
所以目前有如下选择：

1. 单纯 revert 之前的 commit；
2. 把另外两个域名的 `https://` 加上；
3. 在1. 的同时增加一个选项“采用 HTTPS 访问 Bangumi”；
4. 在1. 的同时直接采用 `https://` 访问。

建议是 4. 但可能造成登录失效问题。

**Comment by wxt2005** [comment]
我同意 4，登录失效不是个大问题，哪怕一直用同一个域名过期了也需要重新登录。

**Comment by upsuper** [comment]
浏览器升级了也会要重新登录……

**Comment by no1xsyzy** [comment]
#60 中修复，关闭
