### ISSUE TITLE
[建议]支持按日本播出时间显示每日放送

### ISSUE THREAD

**Issue by zhongfly** [wxt2005/bangumi-list#83]
目前是按大陆播出时间显示每天播出的动画，能否在设置中支持切换成按日本放送时间显示？

**Comment by wxt2005** [comment]
确实按现在这情况感觉按大陆播放时间排序意义不大了。最近抽空改版中，下一版会按日本播放时间排序。

**Comment by wolfan** [comment]
建议新版的加星可以至顶。
既然不按播放时序了，那加一个调整选项，比如预定的某一番一般是在次日有资源，这样就应该有个‘转移次日’或是‘转移n日’的选项就更好了。

**Comment by wolfan** [comment]
建议新版的加星可以至顶。
既然不按播放时序了，那加一个调整选项，比如预定的某一番一般是在次日有资源，这样就应该有个‘转移次日’或是‘转移n日’的选项就更好了。

**Comment by wxt2005** [comment]
感谢建议。新版的置顶功能已加。
至于这个调整选型，我还得再思考下🤔
